wiki:
  # Wiki title
  title: "Test Wiki"

  # Wiki description
  description: "Wiki Description"

  # The theme to use
  theme: "default"

  # Default file to show when going to a namespace
  index: "index"

  # Site pages document root
  document_root: wiki

# Address and port the server listens on
server:
  addr: 0.0.0.0
  port: 8080
